name: Lostprofessions
version: ${project.version}
main: net.lostfables.lughgk.lostprofessions.Lostprofessions
api-version: 1.13
authors: [LughGK, Korvic]
description: A small profession system
website: lostfables.net
depend: [Tythan]
commands:
  limenu:
    description: A lore item menu
    permission: lostprofessions.menu
  liadd:
    description: Add items to the lore items table!
    permission: lostprofessions.additem
